// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_DynLossOptimR_TMBExports
#include <TMB.hpp>
#include "poly_model.hpp"
#include "poly_model_full.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "poly_model") {
    return poly_model(this);
  } else if(model == "poly_model_full") {
    return poly_model_full(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
